# indexing
indexing:
  text:
    data_base_relative_path:
    mode: ""
    threshold: 10
    limit: 10
  image:
    data_base_relative_path: {"data/images/TEST_NB/", "data/images/TEST_RGB/"}
  audio:
    data_base_relative_path: {data/audios/TEST_SON/}
    samples: 1024
    interval: 100

# comparison
comparison:
  image:
    threshold:
  audio:
    threshold:
