# general settings
general:
  data_base_relative_path: "data/"

# indexing settings
indexing:
  text:
    data_base_relative_path:
    mode: ""
    threshold: 10
    limit: 10
  image:
    quantification: 2
  audio:
    samples: 1024
    interval: 100

# comparison settings
comparison:
  image:
    threshold:
  audio:
    threshold:
